spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person
    username: root
    password: 252119

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
